### ISSUE TITLE
trimmomatic can run but some errors.

### ISSUE THREAD

**Issue by decenwang** [timflutre/trimmomatic#10]
Hi All, I am a newcomer in bioinformatics. recently I use the trimmomatic to train myself. First, **I install the trimmomatic by conda**, which means I can execute by command line "trimmomatic PE -threads 4 -phred 33........(as the standard protocol)", it might work but please see below some **errors happened: my question are: 1. why cannot find the TruSeq3-PE.fa? I found the file in ~/miniconda3/pkgs/trimmomatic-0.38-1/share/trimmomatic-0.38-1/adapters. 2. and the other java problems as shown. 
error:** 
trimmomatic PE -phred33 SRR4449813_1_1.fastq SRR4449813_1_2.fastq paired_1_R1_paired.fq.gz unpaired_1_R1_unpaired.fq.gz paired_1_R2_paired.fq.gz unpaired_1_R2_unpaired.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:3 TrimmomaticPE: Started with arguments: -phred33 SRR4449813_1_1.fastq SRR4449813_1_2.fastq paired_1_R1_paired.fq.gz unpaired_1_R1_unpaired.fq.gz paired_1_R2_paired.fq.gz unpaired_1_R2_unpaired.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:3 Multiple cores found: Using 4 threads java.io.****FileNotFoundException: /home/decen/下载/srr/TruSeq3-PE.fa (No such file or directory)**** 
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195) 
at java.io.FileInputStream.<init>(FileInputStream.java:138) 
at org.usadellab.trimmomatic.fasta.FastaParser.parse(FastaParser.java:54)
at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.loadSequences(IlluminaClippingTrimmer.java:110) 
at org.usadellab.trimmomatic.trim.IlluminaClippingTrimmer.makeIlluminaClippingTrimmer(IlluminaClippingTrimmer.java:71) 
at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:32) 
at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:552) 
at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80) 
Input Read Pairs: 3438238 Both Surviving: 3397549 (98.82%) Forward Only Surviving: 37731 (1.10%) Reverse Only Surviving: 2828 (0.08%) Dropped: 130 (0.00%) TrimmomaticPE: Completed successfully

Thanks a lot!

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
