### ISSUE TITLE
Error -- File is too large 

### ISSUE THREAD

**Issue by sdabral05** [timflutre/trimmomatic#12]
hi , 

I am new to this . I am Trimmomatic on human sample and i am getting error of FILE size  is too large .

Terminal scree shot ----

 java -Xmx128g -jar trimmomatic-0.36.jar PE -threads 6 -phred33 /media/haroon/DKVL_3.19/amit_raw_files/RHH031_1.fastq.gz /media/haroon/DKVL_3.19/amit_raw_files/RHH031_2.fastq.gz -baseout Trimmed/RHH031 TRAILING:30
TrimmomaticPE: Started with arguments:
 -threads 6 -phred33 /media/haroon/DKVL_3.19/amit_raw_files/RHH031_1.fastq.gz /media/haroon/DKVL_3.19/amit_raw_files/RHH031_2.fastq.gz -baseout Trimmed/RHH031 TRAILING:30
Using templated Output files: Trimmed/RHH031_1P Trimmed/RHH031_1U Trimmed/RHH031_2P Trimmed/RHH031_2U
java.io.IOException: File too large
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-2" java.lang.RuntimeException: java.io.IOException: File too large
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: File too large
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at org.usadellab.trimmomatic.fastq.FastqSerializer.writeRecord(FastqSerializer.java:63)
	at org.usadellab.trimmomatic.threading.SerializerWorker.run(SerializerWorker.java:45)
	... 1 more
java.io.IOException: File too large

please help to resolve this issues.

Thanks and regards

**Comment by timflutre** [comment]
As explained in the README, I am not the official maintainer of Trimmomatic (I also now prefer to use CutAdapt). For this issue, you should contact Anthony Bolger (http://www.usadellab.org/cms/index.php?page=trimmomatic). Note also that I made this repo with version 0.33 of the code, but A. Bolger may have improved the code since.
