### ISSUE TITLE
Trimlog file creation error

### ISSUE THREAD

**Issue by roshni-b** [timflutre/trimmomatic#7]
I am processing in Paired End Mode, having specified the [-trimlog <logFile>] this is the error message I am getting: 

_Exception in thread "main" java.lang.RuntimeException: Unknown trimmer: /home/venkat/Desktop/output_reverse_unpaired.fq.gz
	at org.usadellab.trimmomatic.trim.TrimmerFactory.makeTrimmer(TrimmerFactory.java:70)
	at org.usadellab.trimmomatic.Trimmomatic.createTrimmers(Trimmomatic.java:59)
	at org.usadellab.trimmomatic.TrimmomaticPE.run(TrimmomaticPE.java:536)
	at org.usadellab.trimmomatic.Trimmomatic.main(Trimmomatic.java:80)_

**Comment by ShevchenkoAlla** [comment]
Hello
I am having the same trouble and can't find the solution?
How did you solve it?
Thanks
